[build]
    environment = { PHP_VERSION = "7.4" }

    command = "npm run staging"
    publish = "build_staging"

[context.production]
    command="npm run prod"
    publish="build_production"

[[redirects]]
    from = "/youtube/*"
    to = "https://www.youtube.com/c/JustSteveKing/videos"
    status = 200
      force = true # COMMENT: ensure that we always redirect
      headers = {X-From = "Netlify"}
    
[[redirects]]
    from = "/adaptern-pattern/"
    to = "/adapter-pattern/"
    status = 200
      force = true # COMMENT: ensure that we always redirect
      headers = {X-From = "Netlify"}