name: Publish Posts

on:
  schedule:
    - cron: "0 8-22 * * *"
  push:

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: scheduled-deploy
        uses: wei/curl@master
        with:
          args: -X POST -d {} "${{ secrets.NETLIFY_BUILD_HOOK }}"